[package]
name = "plurr"
version = "0.2.0"
authors = ["Julen Ruiz Aizpuru <julenx@gmail.com>"]
edition = "2018"
description = "A library for handling plurals/genders/conditionals."
license = "MIT"
readme = "README.md"
repository = "https://github.com/loctools/plurr/"


[dependencies]
